### ISSUE TITLE
Prompts for inputs even when Arguments are passed

### ISSUE THREAD

**Issue by datsabk** [hubotio/generator-hubot#111] opened 2024-02-28 20:06 UTC
Hello @joeyguerra , 
After your recent changes, the conditional prompts got converted to permanent prompts. 

```
if (!this.options.owner) {
        prompts.push({
          name: 'botOwner',
          message: 'Owner',
          default: botOwner
        })
      }
```
This is how the prompts are expected to be. Instead, it now pushes all prompts even if options are passed. Could you please look into fixing the same.

**Comment by joeyguerra** [comment] 2024-02-28 21:17
@datsabk can you write a failing test for the scenario you're running into? Please note that the default username and email comes from the machine's `git` configured username and email.

**Comment by datsabk** [comment] 2024-02-28 21:20
Hello @joeyguerra ,
I basically try passing the options via arguments. Ideally it should not prompt me when those options are passed as flag. 

my command looks like `yo hubot --owner something --name gitbot....`

**Comment by joeyguerra** [comment] 2024-02-28 21:24
I see. I'm no longer making feature requests to this package because the current recommended way to generate a Hubot instance is as documented in the [Hubot repo readme](https://github.com/hubotio/hubot). Would you mind trying that instead? But I haven't added the ability to set the owner properties via cli arguments. You would just update the `package.json` directly with those values.

```sh
npx hubot --create myhubot --adapter @hubot-friends/hubot-slack
```

Where `myhubot` is the folder you want to create the bot in.

**Comment by hontarenko** [comment] 2024-04-01 06:46
@joeyguerra I have the same issue with prompts for inputs even when arguments are passed. As a result, my image build broke :(

**Comment by hontarenko** [comment] 2024-04-01 12:48
@joeyguerra Сan you provide an example of Dockerfile with recommended installation way hubot-slack?

**Comment by joeyguerra** [comment] 2024-04-01 13:33
@hontarenko what mage are you currently using? What command do you run?

**Comment by hontarenko** [comment] 2024-04-01 13:42
```

FROM node:20.12

ARG GITHUB_TOKEN
ARG HUBOT_SLACK_TOKEN


ENV GITHUB_TOKEN="${GITHUB_TOKEN}" \
    HUBOT_SLACK_TOKEN="${HUBOT_SLACK_TOKEN}"


RUN npm i -g yo@5.0.0 generator-hubot@2.0.1 && \
    addgroup hubot && \
    adduser --disabled-password --gecos '' --ingroup hubot hubot && \
    adduser hubot hubot

USER hubot

WORKDIR /home/hubot

RUN yo hubot --adapter=slack \
    --owner="test" \
    --name="HuBot" \
    --description="HuBot for github actions" \
    --defaults && \
    npm i axios@1.6.8

COPY trigger-workflow.js scripts/

CMD HUBOT_SLACK_TOKEN="${HUBOT_SLACK_TOKEN}" ./bin/hubot --adapter slack
```

**Comment by joeyguerra** [comment] 2024-04-01 16:48
@hontarenko I pushed a fix for the issue. Please update your Dockerfile to install the latest `generator-hubot` and let me know.

Please note that I'm no longer maintaining this template. I recommend using `npx hubot --create ` as described in the [Hubot Readme](https://github.com/hubotio/hubot/).

**Comment by joeyguerra** [comment] 2024-04-01 18:53
If you're interested in using the latest version of Hubot and the new hubot-slack adapter that works with the latest version of Hubot, here's an updated `Dockerfile` for it:

```docker

FROM node:21-alpine

ARG GITHUB_TOKEN
ARG HUBOT_SLACK_TOKEN


ENV GITHUB_TOKEN="${GITHUB_TOKEN}" \
    # HUBOT_SLACK_TOKEN="${HUBOT_SLACK_TOKEN}" \
    HUBOT_SLACK_APP_TOKEN="${HUBOT_SLACK_APP_TOKEN}" \
    HUBOT_SLACK_BOT_TOKEN="${HUBOT_SLACK_BOT_TOKEN}"


RUN addgroup hubot && \
    adduser --disabled-password --gecos '' --ingroup hubot hubot && \
    adduser hubot hubot

USER hubot

WORKDIR /home/hubot

# RUN yo hubot --adapter=slack \
#     --owner="test" \
#     --name="HuBot" \
#     --description="HuBot for github actions" \
#     --defaults && \
#     npm i axios@1.6.8
RUN npx hubot --create . --adapter @hubot-friends/hubot-slack --name "HuBot" && \
    npm i axios@1.6.8

COPY trigger-workflow.js scripts/

CMD HUBOT_SLACK_APP_TOKEN="${HUBOT_SLACK_APP_TOKEN}" HUBOT_SLACK_BOT_TOKEN="${HUBOT_SLACK_BOT_TOKEN}" npm start -- --name "HuBot"
```

**Comment by hontarenko** [comment] 2024-04-02 08:15
@joeyguerra With latest version generator-hubot, i am getting an error:
![image](https://github.com/hubotio/generator-hubot/assets/94844601/51af50e3-a303-4df6-b4c4-2eaf9f354868)

`./bin/hubot --adapter slack`

**Comment by joeyguerra** [comment] 2024-04-02 14:47
@hontarenko I think that error is caused by using the latest version of Hubot (which is installed by the yeoman Hubot generator) and the old Slack Adapter (which is incompatible with the latest version of Hubot).

I think your options are to downgrade Hubot and all of the default Hubot scripts or update to the compatible Slack Adapter (which requires you to get a Slack app token AND a Slack Bot Token https://github.com/hubot-friends/hubot-slack).

I think you can downgrade Hubot and it's default scripts with the following:

In your original version Dockerfile:

```docker
RUN yo hubot --adapter=slack \
    --owner="test" \
    --name="HuBot" \
    --description="HuBot for github actions" \
    --defaults && \
    npm i axios@1.6.8 hubot@4 hubot-redis-brain@2 hubot-diagnostics@1
```

Looking forward to hearing what path you take.

**Comment by hontarenko** [comment] 2024-04-02 17:02
@joeyguerra With downgraded versions i got dependency conflict:

![image](https://github.com/hubotio/generator-hubot/assets/94844601/ad7a21b3-ede9-4bc3-acfb-cc8aa542aeca)

And if using `--force`:  `{"level":50,"time":1712071439122,"pid":93,"hostname":"40391f503aab","name":"HuBot","msg":"Cannot load adapter slack - Error: Cannot find module 'hubot-slack'\nRequire stack:\n- /home/hubot/node_modules/hubot/src/robot.js\n- /home/hubot/node_modules/hubot/es2015.js\n- /home/hubot/node_modules/hubot/index.js\n- /home/hubot/node_modules/hubot/bin/hubot.js\n- /home/hubot/node_modules/hubot/bin/hubot"}`

**Comment by joeyguerra** [comment] 2024-04-02 20:31
Ok. `--force` might work. Looks like the error is because `hubot-slack` isn't installed. I suspect it's because the latest generator-hubot isn't installing it correctly.

Can you please try installing it:

```docker
RUN yo hubot --adapter=slack \
    --owner="test" \
    --name="HuBot" \
    --description="HuBot for github actions" \
    --defaults && \
    npm i axios@1.6.8 hubot@4 hubot-redis-brain@2 hubot-diagnostics@1 hubot-slack --force
```

**Comment by hontarenko** [comment] 2024-04-03 11:52
I think trouble in this function https://github.com/hubotio/hubot/blob/main/src/Robot.mjs#L520-L522

**Comment by hontarenko** [comment] 2024-04-03 11:53
```
{"level":50,"time":1712144903526,"pid":178,"hostname":"67f22d073dea","name":"HuBot","msg":"Cannot load adapter [no path set] slack - TypeError: (intermediate value).default.use is not a function"}
file:///home/hubot/node_modules/hubot/src/Robot.mjs:523
    return await (await import(adapterPath)).default.use(this)
                                                     ^

TypeError: (intermediate value).default.use is not a function
    at Robot.importAdapterFrom (file:///home/hubot/node_modules/hubot/src/Robot.mjs:523:54)
    at async Robot.requireAdapterFrom (file:///home/hubot/node_modules/hubot/src/Robot.mjs:519:12)
    at async Robot.loadAdapter (file:///home/hubot/node_modules/hubot/src/Robot.mjs:503:26)
    at async file:///home/hubot/node_modules/hubot/bin/Hubot.mjs:132:3

Node.js v20.12.0
```

**Comment by joeyguerra** [comment] 2024-04-03 14:30
Yes. The code assumes that the adapter will be an ESM. The old slack adapter is not. It’s a CJS module.

**Comment by joeyguerra** [comment] 2024-04-03 14:40
That error suggests that Hubot version 4 is not being installed. The of the code you posted is in the newer versions of Hubot.

**Comment by joeyguerra** [comment] 2024-04-03 15:35
The following `Dockerfile` seems to work, but I still recommend you moving to the latest version of Hubot with the new [Slack Adapter](https://github.com/hubot-friends/hubot-slack) because the configuration defined below is using unmaintained versions of modules that have a possibility of not working together.

```dockerfile
FROM node:20.12

ARG GITHUB_TOKEN
ARG HUBOT_SLACK_TOKEN

ENV GITHUB_TOKEN="${GITHUB_TOKEN}" \
    HUBOT_SLACK_TOKEN="${HUBOT_SLACK_TOKEN}"

RUN npm i -g yo generator-hubot && \
    addgroup hubot && \
    adduser --disabled-password --gecos '' --ingroup hubot hubot && \
    adduser hubot hubot

USER hubot

WORKDIR /home/hubot

RUN yo hubot --owner="test" \
    --name="HuBot" \
    --description="HuBot for github actions" \
    --defaults
RUN npm i axios@1.6.8 hubot@4 hubot-slack
RUN npm i hubot-redis-brain@2 hubot-diagnostics@1 coffeescript@1 --force
RUN rm scripts/Example.mjs

COPY trigger-workflow.js scripts/

CMD ["npm", "start", "--", "--adapter", "slack", "--name", "HuBot"]
```

**Comment by hontarenko** [comment] 2024-04-03 19:22
Thanks! Problem solved :)

**Comment by joeyguerra** [comment] 2024-04-03 21:58
You're welcome. I'm curious, care to share what you're using Hubot for? Is it valuable?

**Comment by hontarenko** [comment] 2024-04-04 11:54
We are using Hubot for triggering github actions workflows with different parameters

**Comment by joeyguerra** [comment] 2024-04-04 17:54
@hontarenko What makes it more attractive than just using the Github Actions UI?

**Comment by hontarenko** [comment] 2024-04-05 07:20
Because I use slack integration with github to run github actions workflows from slack commands. Such a business need

**Closed** 2024-04-05 13:51 UTC
Labels: released
